export const FETCH_ALL_USERS_PENDING = "FETCH_ALL_USERS_PENDING";
export const FETCH_ALL_USERS_SUCCESS = "FETCH_ALL_USERS_SUCCESS";
export const FETCH_ALL_USERS_FAILED = "FETCH_ALL_USERS_FAILED";

export const FETCH_ONE_USER_PENDING = "FETCH_ONE_USER_PENDING";
export const FETCH_ONE_USER_SUCCESS = "FETCH_ONE_USER_SUCCESS";
export const FETCH_ONE_USER_FAILED = "FETCH_ONE_USER_FAILED";

export const ADD_NEW_USER_PENDING = "ADD_NEW_USER_PENDING";
export const ADD_NEW_USER_SUCCESS = "ADD_NEW_USER_SUCCESS";
export const ADD_NEW_USER_FAILED = "ADD_NEW_USER_FAILED";

export const REMOVE_USER_PENDING = "REMOVE_USER_PENDING";
export const REMOVE_USER_SUCCESS = "REMOVE_USER_SUCCESS";
export const REMOVE_USER_FAILED = "REMOVE_USER_FAILED";

export const BASE_URL = "http://192.168.1.5:8000/users";
