export const FETCH_ALL_MOVIES_PENDING = "FETCH_ALL_MOVIES_PENDING";
export const FETCH_ALL_MOVIES_SUCCESS = "FETCH_ALL_MOVIES_SUCCESS";
export const FETCH_ALL_MOVIES_FAILED = "FETCH_ALL_MOVIES_FAILED";

export const FETCH_ONE_MOVIE_PENDING = "FETCH_ONE_MOVIE_PENDING";
export const FETCH_ONE_MOVIE_SUCCESS = "FETCH_ONE_MOVIE_SUCCESS";
export const FETCH_ONE_MOVIE_FAILED = "FETCH_ONE_MOVIE_FAILED";

export const ADD_NEW_MOVIE_PENDING = "ADD_NEW_MOVIE_PENDING";
export const ADD_NEW_MOVIE_SUCCESS = "ADD_NEW_MOVIE_SUCCESS";
export const ADD_NEW_MOVIE_FAILED = "ADD_NEW_MOVIE_FAILED";

export const REMOVE_MOVIE_PENDING = "REMOVE_MOVIE_PENDING";
export const REMOVE_MOVIE_SUCCESS = "REMOVE_MOVIE_SUCCESS";
export const REMOVE_MOVIE_FAILED = "REMOVE_MOVIE_FAILED";

export const EDIT_MOVIE_SUCCESS = "EDIT_MOVIE_SUCCESS";
export const EDIT_MOVIE_FAILED = "EDIT_MOVIE_FAILED";
export const EDIT_MOVIE_PENDING = "EDIT_MOVIE_PENDING";

export const BASE_URL = "http://192.168.1.2:8000/movies";
