export const FETCH_ALL_SHOWUPDATES_PENDING = "FETCH_ALL_SHOWUPDATES_PENDING";
export const FETCH_ALL_SHOWUPDATES_SUCCESS = "FETCH_ALL_SHOWUPDATES_SUCCESS";
export const FETCH_ALL_SHOWUPDATES_FAILED = "FETCH_ALL_SHOWUPDATES_FAILED";

export const FETCH_ONE_SHOWUPDATE_PENDING = "FETCH_ONE_SHOWUPDATE_PENDING";
export const FETCH_ONE_SHOWUPDATE_SUCCESS = "FETCH_ONE_SHOWUPDATE_SUCCESS";
export const FETCH_ONE_SHOWUPDATE_FAILED = "FETCH_ONE_SHOWUPDATE_FAILED";

export const ADD_NEW_SHOWUPDATE_PENDING = "ADD_NEW_SHOWUPDATE_PENDING";
export const ADD_NEW_SHOWUPDATE_SUCCESS = "ADD_NEW_SHOWUPDATE_SUCCESS";
export const ADD_NEW_SHOWUPDATE_FAILED = "ADD_NEW_SHOWUPDATE_FAILED";

export const REMOVE_SHOWUPDATE_PENDING = "REMOVE_SHOWUPDATE_PENDING";
export const REMOVE_SHOWUPDATE_SUCCESS = "REMOVE_SHOWUPDATE_SUCCESS";
export const REMOVE_SHOWUPDATE_FAILED = "REMOVE_SHOWUPDATE_FAILED";

export const BASE_URL = "http://192.168.1.3:8000/showupdates";
