export const FETCH_ALL_SHOWS_PENDING = "FETCH_ALL_SHOWS_PENDING";
export const FETCH_ALL_SHOWS_SUCCESS = "FETCH_ALL_SHOWS_SUCCESS";
export const FETCH_ALL_SHOWS_FAILED = "FETCH_ALL_SHOWS_FAILED";

export const FETCH_ONE_SHOW_PENDING = "FETCH_ONE_SHOW_PENDING";
export const FETCH_ONE_SHOW_SUCCESS = "FETCH_ONE_SHOW_SUCCESS";
export const FETCH_ONE_SHOW_FAILED = "FETCH_ONE_SHOW_FAILED";

export const ADD_NEW_SHOW_PENDING = "ADD_NEW_SHOW_PENDING";
export const ADD_NEW_SHOW_SUCCESS = "ADD_NEW_SHOW_SUCCESS";
export const ADD_NEW_SHOW_FAILED = "ADD_NEW_SHOW_FAILED";

export const REMOVE_SHOW_PENDING = "REMOVE_SHOW_PENDING";
export const REMOVE_SHOW_SUCCESS = "REMOVE_SHOW_SUCCESS";
export const REMOVE_SHOW_FAILED = "REMOVE_SHOW_FAILED";

export const EDIT_SHOW_SUCCESS = "EDIT_SHOW_SUCCESS";
export const EDIT_SHOW_FAILED = "EDIT_SHOW_FAILED";
export const EDIT_SHOW_PENDING = "EDIT_SHOW_PENDING";

export const BASE_URL = "http://192.168.1.3:8000/shows";
